import Cabecalho from "@/components/Cabecalho/Cabecalho";
import Rodape from "@/components/Rodape/Rodape";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Projeto Atlas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="shortcut icon" href="/img/logo-porto.png" type="image/x-icon" />
      </head>
      <body className="font-righteous flex flex-col justify-between h-screen bg-back-image">
        <Cabecalho />
        {children}
        <Rodape />
      </body>
    </html>
  );
}