import Cabecalho from "@/components/Cabecalho/Cabecalho";
import Rodape from "@/components/Rodape/Rodape";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Projeto Atlas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="font-righteous">
        <Cabecalho />
        {children}
        <Rodape />
      </body>
    </html>
  );
}
